# TO NOTE: this is an example config file!

# TO NOTE: this default config file can be used when need to run --unlock.

# This and the config/key.py file are the only files that should be edited to
# run imputation using the snakemake_imputation repo. A new config file should
# be made for each different imputation.

### TODO: Update pipeline settings
# Default filters of MAF 0 and Rsq 0.3 are applied after imputation.
chr: [6]  # list of chromosome numbers with format [1,10,22]
orig_build: "hg19"  #  either "hg19" or "hg38"
to_build: "hg38"  # either "hg19" or "hg38"
imp: "topmed"  # should be 'topmed', 'mich_hla_v1', 'mich_hla_v2', 'mich_1kg_p3_v5', 'mich_hrc'
imp_rsq_filt: "0"  # DEFAULT: "0", filter to apply on imputation server (0, 0.001, 0.1, 0.2, or 0.3)
imp_name: "test_daisy_full_qc"  # job name for imputation server
imp_job_id: "job-20251108-155514-776"  # should be "job-####-##-###"
zip_pw: ""  # add from email when imputed job finishes
opt: "gt"  # DEFAULT: "gt", option for "gt" only or "all" dosage information (much slower)
use_cont: false  # DEFAULT: true, true to use container, false to use local machine
# sexcheck: [0.8, 0.2]  # DEFAULT: [0.8, 0.2]

### TODO: Update host paths outside container
# PLINK1.9 file prefix with path - must be single file, but can contain one or more chr
plink_prefix: "/Users/slacksa/temp_data/daisy/new_tm_imp_test/input/daisyraw0_sex_study_ids"
# OPTIONAL: ID list (FID IID) want to run imputation for, if none use ""
id_list: "/Users/slacksa/temp_data/daisy/new_tm_imp_test/input/daisy_study_id_list.txt"
# OPTIONAL: ID list to calculate HWE filtering in (likely controls)
id_list_hwe: "/Users/slacksa/temp_data/daisy/new_tm_imp_test/input/ctrls_id_list.txt"
# Top-level directory for all output
out_dir: "/Users/slacksa/temp_data/daisy/new_tm_imp_test_alt_download"
  #TODO: this must contain the pre-QC PLINK1.9 file at out_dir/pre_qc/pre_qc!
# Repo with snakemake pipeline
repo: "/Users/slacksa/repos/imputation"

### Container paths - should not be changed
plink_dir_cont: "/input_data"
id_list_dir_cont: "/id_list"
out_dir_cont: "/output_data"
repo_cont: "/repo"
